print("A short history on Donald Knuth")
print("Knuth, born in 1938, was a computer scientist, mathematician, and professor at Stanford University.")
print("An esteemed scientist and author, Knuth wrote \"The Art of Programming\" and popularized asymptotic notation.")
print("He also wanted more people to be interested and take action in the programming realm, pushing for the US to issue software patents to incentivize programming.")
text = input("Have you heard of this person before? Aren't they great?")
print("You said this?:")
print(text)
print("They are pretty cool, aren't they.")
